#!/usr/bin/env bash
# transfer file from client to server
file=$1
ip=$2
username=$3
key=$4
if [ $# -eq 4 ]; then
    scp -i $key $file "$username"@"$ip":/home/"${username}"
else
    echo 'Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY'
fi