#!/usr/bin/env bash
#Double the number of webservers
sudo apt update
sudo apt install haproxy -y
sudo sh -c 'echo "\nlisten myserver\n\tbind *:80\n\tbalance roundrobin\n\tserver 338578-web-01 100.26.211.99:80 check\n\tserver 338578-web-02 54.80.43.239:80 check\n" >> /etc/haproxy/haproxy.cfg'
sudo service haproxy restart