#!/usr/bin/env bash
#display bad luck on 4th line and good luck in 8th line

a=0
while [ $a -lt 10 ]
do
	if [ $a -eq 3 ]
	then
		echo "bad luck"
	elif [ $a -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( a++ ))
done
